version: '3'

services:
    web:
        container_name: 'instaclone_web'
        build: .
        ports:
            - "8000:8000"
        environment:
            - INSTACLONE_DJANGO_SECRET_KEY
            - INSTACLONE_DJANGO_DEBUG_MODE
            - TESTMAIL_USER
