version: '3'

services:
    web:
        container_name: 'django'
        build: instaclone
        volumes:
            - static:/usr/src/app/static
            - media:/usr/src/app/media
        ports:
            - "8000:8000"
        environment:
            - INSTACLONE_DJANGO_SECRET_KEY
            - INSTACLONE_DJANGO_DEBUG_MODE
            - INSTACLONE_MAIL_USER
            - INSTACLONE_MAIL_PASS
    server:
        container_name: 'nginx'
        build: nginx
        volumes:
            - static:/static
            - media:/media
        ports:
            - "80:80"

volumes:
    static:
    media:
