version: '3'

services:
    web:
        container_name: 'django'
        build: instaclone
        volumes:
            - static:/usr/src/app/static
            - media:/usr/src/app/media
        environment:
            - INSTACLONE_DJANGO_SECRET_KEY
            - INSTACLONE_DJANGO_DEBUG_MODE
            - INSTACLONE_MAIL_USER
            - INSTACLONE_MAIL_PASS
    server:
        container_name: 'nginx'
        build: nginx
        volumes:
            - static:/static
            - media:/media
        ports:
            - "80:80"
    rabbit:
        container_name: 'rabbitmq'
        image: rabbitmq
        ports:
            - "5672:5672"
    celery:
        container_name: 'celery'
        build:
            context: instaclone
            dockerfile: celery.Dockerfile
        environment:
            - INSTACLONE_DJANGO_SECRET_KEY
            - INSTACLONE_DJANGO_DEBUG_MODE
            - INSTACLONE_MAIL_USER
            - INSTACLONE_MAIL_PASS
        depends_on:
            - rabbit

volumes:
    static:
    media:
