# Generated by Django 4.0.3 on 2022-04-17 07:53

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to=feed.models._user_content_dir),
        ),
    ]
